variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # make firefox run without a display
  MOZ_HEADLESS: "1"

cache:
  paths:
    - .cache/pip

stages:
  - build-and-test
  - staging-deploy
  - staging-test


test:
  image: python:slim
  stage: build-and-test

  before_script:
    # install firefox
    - apt update -y && apt install -y
      curl
      firefox-esr
      openssh-client
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

  script:
    - pip install -r requirements.txt
    - pip install selenium

    # unit tests
    - python src/manage.py test lists accounts
    # (if those pass) all tests, incl. functional. yes we need that cd.
    - cd src && python manage.py test


# build and test against docker image
build:
  image: docker:git
  services:
    - docker:dind
  stage: build-and-test

  script:
    - docker build
      -t registry.gitlab.com/hjwp/book-example:$CI_COMMIT_SHA
      .
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push
      registry.gitlab.com/hjwp/book-example:$CI_COMMIT_SHA

    # TODO: $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME:$CI_COMMIT_SHA

deploy:
  stage: staging-deploy
  image: python:slim
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"

  before_script:
    - apt update -y && apt install -y
      curl
      openssh-client
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

  script:
    - pip install -r requirements.txt
    - pip install ansible
    # download secure files to get private key
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - chmod 600 .secure_files/*

    - ansible-playbook
      --private-key=.secure_files/keypair-for-gitlab
      --user=elspeth
      -i staging.ottg.co.uk,
      -vvv
      ${PWD}/infra/deploy-playbook.yaml

test-staging:
  image: python:slim
  stage: staging-test

  before_script:
    - apt update -y && apt install -y
      curl
      firefox-esr
      openssh-client
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

  script:
    - pip install -r requirements.txt
    - pip install selenium
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - chmod 600 .secure_files/*
    - env
      TEST_SERVER=staging.ottg.co.uk
      SSH_PRIVATE_KEY_PATH=.secure_files/keypair-for-gitlab
      python src/manage.py test functional_tests


# could add prod deploy here
