variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # make firefox run without a display
  MOZ_HEADLESS: "1"

cache:
  paths:
    - .cache/pip

stages:
  - ci
  - cd


test:
  image: python:slim
  stage: ci

  before_script:
    # install firefox
    # TODO temporarily uncommented
    # - apt update -y && apt install -y firefox-esr
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

  script:
    - pip install -r requirements.txt
    - pip install selenium

    # unit tests
    - python src/manage.py test lists accounts
    # (if those pass) all tests, incl. functional. yes we need that cd.
    # TODO temporarily uncommented fix
    # - cd src && python manage.py test


# build and test against docker image
build:
  image: docker:git
  services:
    - docker:dind
  stage: ci

  script:
    - docker build
      -t registry.gitlab.com/hjwp/book-example:$CI_COMMIT_SHA
      .
    # - docker run
    #   -d
    #   -p 8888:8888
    #   -e DJANGO_SECRET_KEY=sekrit
    #   -e DJANGO_ALLOWED_HOST=localhost
    #   -t superlists
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push
      registry.gitlab.com/hjwp/book-example:$CI_COMMIT_SHA

    # TODO: $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME:$CI_COMMIT_SHA

    # TODO:
    # --mount type=bind,source=./src/db.sqlite3,target=/src/db.sqlite3
    # -e EMAIL_PASSWORD

    # - TEST_SERVER=localhost:8888 python src/manage.py test functional_tests

    # # deploy to staging
    # - pip install ansible docker
    # - cat infra/deploy-playbook.yaml
    # - ansible-playbook
    #   --user=elspeth
    #   -i staging.ottg.co.uk,
    #   -vv
    #   ${PWD}/infra/deploy-playbook.yaml
    #
deploy:
  stage: cd
  image: python:slim

  before_script:
    # install firefox
    # TODO temporarily uncommented
    # - apt update -y && apt install -y firefox-esr
    - apt update -y && apt install -y
      curl
      openssh-client
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

  script:
    - pip install -r requirements.txt
    - pip install ansible
    # download secure files to get private key
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - ls .secure-files

    - ansible-playbook
      --private-key=.secure-files/keypair-for-gitlab
      --user=elspeth
      -i staging.ottg.co.uk,
      -vv
      ${PWD}/infra/deploy-playbook.yaml
