# Generated by Django 5.1.1 on 2024-09-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_alter_item_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
    ]
