# Generated by Django 4.2.13 on 2024-08-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_alter_item_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
    ]
