# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
