when:
  - event: push
    branch: chapter_25_CI

steps:
  - name: test
    image: python:slim
    environment:
      # make firefox run without a display
      MOZ_HEADLESS: "1"
    commands:
      # install firefox
      - apt-get update -y && apt-get install -y firefox-esr
      - python --version ; pip --version  # For debugging
      - pip install virtualenv
      - virtualenv .venv
      - .venv/bin/pip install -r requirements.txt
      - .venv/bin/pip install selenium
      # unit tests
      - .venv/bin/python src/manage.py test lists accounts
      # (if those pass) all tests, incl. functional. yes we need that cd.
      - cd src && ../.venv/bin/python manage.py test
